### ISSUE TITLE
findByValue

### ISSUE THREAD

**Issue by bryandobberstein** [lynnjosse/techjobs-console-java#1]
`

  String searchString = jobPair.getValue();
  String lowerSearchString = searchString.toLowerCase();
  String lowerValue = value.toLowerCase();
  if (lowerSearchString.contains(lowerValue))

`
This can be simplified. My version has these four line down to two while still being readable.

Also, start commenting your code. Develop good habits now. Once you're out in the world, whether you are revisiting code you wrote a year ago or you move up the ladder and someone comes in behind you who will have to make sense of your code comments make it easier.

**Comment by lynnjosse** [comment]
issue didn't close itself above so here I am closing it.

**Comment by lynnjosse** [comment]
oops.
